syntax = "proto2";

package protolib;

option cc_enable_arenas = true;

message RequestMessage {
    optional P2RequestMessage p2 = 1;
    optional P6RequestMessage p6 = 2;
}

message P2RequestMessage {
    optional fleetbench_rpc_P2_request_Message0  m_0 = 1;
}

message P6RequestMessage {
    optional fleetbench_rpc_P6_request_Message1   m_1 = 1;
}

message fleetbench_rpc_P2_request_Message0 {
  repeated int32 f_0 = 1;
  optional bytes f_1 = 2;
  optional bytes f_2 = 8;
  optional bytes f_3 = 11;
  optional bytes f_4 = 14;
  repeated bytes f_5 = 18;
  repeated bytes f_6 = 20;
  optional bytes f_7 = 21;
  optional bytes f_8 = 25;
  optional bytes f_9 = 27;
  message M1 {
    optional bytes f_0 = 3;
    optional bytes f_1 = 9;
    optional int64 f_2 = 12;
    optional int64 f_3 = 18;
    repeated int32 f_4 = 20;
    optional int64 f_5 = 23;
    repeated bytes f_6 = 30;
    optional bool f_7 = 38;
    message M4 {
      optional int32 f_0 = 1;
      optional bytes f_1 = 5;
      optional int64 f_2 = 9;
      optional int32 f_3 = 14;
      repeated int32 f_4 = 22;
      optional bytes f_5 = 25;
      optional bytes f_6 = 29;
      enum E1 {
        E1_UNSPECIFIED = 0;
        E1_CONST_1 = 115;
        E1_CONST_2 = 62;
        E1_CONST_3 = 121;
        E1_CONST_4 = 9;
        E1_CONST_5 = 96;
      }
      optional E1 f_7 = 37;
      optional bytes f_8 = 44;
      repeated bytes f_9 = 46;
      optional int32 f_10 = 48;
      message M6 {
        optional uint64 f_0 = 2;
        optional uint64 f_1 = 6;
        message M7 {
          optional fixed64 f_0 = 4;
          optional bool f_1 = 8;
          optional int64 f_2 = 10;
          optional bytes f_3 = 15;
          optional bytes f_4 = 17;
          optional fixed64 f_5 = 21;
          optional int32 f_6 = 26;
          optional bytes f_7 = 31;
          optional bytes f_8 = 37;
          repeated int32 f_9 = 40;
          optional bool f_10 = 48;
          repeated int32 f_11 = 49;
          message M8 {
            optional int64 f_0 = 3;
            optional int64 f_1 = 7;
            optional int64 f_2 = 11;
            optional uint64 f_3 = 14;
            repeated bytes f_4 = 21;
            optional int64 f_5 = 23;
            optional int32 f_6 = 24;
            optional int64 f_7 = 27;
            optional int32 f_8 = 30;
            optional bytes f_9 = 36;
            optional fixed32 f_10 = 38;
            optional uint64 f_11 = 41;
            optional int64 f_12 = 45;
            optional fixed32 f_13 = 48;
            optional int32 f_14 = 52;
            optional int32 f_15 = 57;
            optional bytes f_16 = 61;
            message M9 {
              optional bytes f_0 = 2;
            }
            optional M9 f_66 = 66;
            message M10 {
              optional uint64 f_0 = 3;
              optional int64 f_1 = 6;
              enum E2 {
                E2_UNSPECIFIED = 0;
                E2_CONST_1 = 114;
                E2_CONST_2 = 81;
                E2_CONST_3 = 41;
                E2_CONST_4 = 72;
                E2_CONST_5 = 75;
              }
              optional E2 f_2 = 9;
            }
            optional M10 f_69 = 69;
          }
          optional M8 f_51 = 51;
        }
        optional M7 f_10 = 10;
      }
      optional M6 f_50 = 50;
    }
    optional M4 f_41 = 41;
  }
  optional M1 f_32 = 32;
  message M2 {
    optional bool f_0 = 4;
    optional fixed64 f_1 = 7;
    optional fixed64 f_2 = 10;
    optional bytes f_3 = 15;
    optional bytes f_4 = 20;
    optional int32 f_5 = 24;
    optional bytes f_6 = 26;
    optional bytes f_7 = 29;
    optional int64 f_8 = 31;
    optional uint64 f_9 = 34;
    optional bytes f_10 = 39;
    optional bool f_11 = 41;
    optional int64 f_12 = 44;
    message M3 {
      optional int32 f_0 = 5;
      optional bytes f_1 = 6;
      repeated bytes f_2 = 7;
      message M5 {
        repeated int32 f_0 = 1;
      }
      optional M5 f_12 = 12;
    }
    optional M3 f_46 = 46;
  }
  optional M2 f_39 = 39;
}

message fleetbench_rpc_P6_request_Message1 {
  enum E1 {
    E1_UNSPECIFIED = 0;
    E1_CONST_1 = 5;
    E1_CONST_2 = 8;
    E1_CONST_3 = 63;
    E1_CONST_4 = 17;
    E1_CONST_5 = 92;
  }
  repeated E1 f_0 = 1;
  repeated bytes f_1 = 2 ;
  optional fixed32 f_2 = 3;
  repeated bytes f_3 = 4 ;
  optional bytes f_4 = 6;
  optional int32 f_5 = 7;
  optional int32 f_6 = 8;
  enum E2 {
    E2_UNSPECIFIED = 0;
    E2_CONST_1 = 7;
    E2_CONST_2 = 77;
    E2_CONST_3 = 2;
    E2_CONST_4 = 1;
    E2_CONST_5 = 114; // write thisj
  }
  repeated E2 f_7 = 9;
  enum E3 {
    E3_UNSPECIFIED = 0;
    E3_CONST_1 = 56;
    E3_CONST_2 = 80;
    E3_CONST_3 = 94;
    E3_CONST_4 = 92;
    E3_CONST_5 = 84;
  }
  repeated E3 f_8 = 11;
  optional bool f_9 = 12;
  optional bytes f_10 = 13;
  optional int32 f_11 = 14;
  repeated bytes f_12 = 15 ;
  optional fixed32 f_13 = 16;
  optional int32 f_14 = 17;
  optional bool f_15 = 18;
  optional bytes f_16 = 20;
  optional int32 f_17 = 21;
  optional fixed32 f_18 = 22;
  optional bytes f_19 = 23;
  message M1 {
    enum E4 {
      E4_UNSPECIFIED = 0;
      E4_CONST_1 = 97;
      E4_CONST_2 = 93;
      E4_CONST_3 = 38;
      E4_CONST_4 = 19;
      E4_CONST_5 = 87;
    }
    repeated E4 f_0 = 1;
  }
  optional M1 f_25 = 25;
  message M2 {
    repeated bytes f_0 = 1 ;
    optional fixed32 f_1 = 2;
    optional fixed32 f_2 = 3;
    optional bool f_3 = 4;
    optional bool f_4 = 5;
  }
  optional M2 f_26 = 26;
}

message SimpleMessage {
  enum MyEnum {
    MyEnum_UNSPECIFIED = 0;
    MyEnum_CONST_1 = 1;
  }
  repeated MyEnum e_2 = 2;
}
