xilinx_u250_grpc_base:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithNIC_FireSimGRPCConfig
  PLATFORM_CONFIG: Remove_GRPCQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 3-2
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_grpc_p1:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithNIC_FireSimGRPCConfig
  PLATFORM_CONFIG: Extract_GRPCQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 3-0
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_grpc_p2:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: WithNIC_FireSimGRPCConfig
  PLATFORM_CONFIG: Extract_GRPCQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 3-1
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: TIMING
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml
