### Tester BR's for Rocket separated from SoC

xilinx_u250_grpc_minimal:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimRocketConfig
  PLATFORM_CONFIG: Preserve_Remove_MinQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 2-1
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_grpc_minimal2:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimRocketConfig
  PLATFORM_CONFIG: Preserve_Extract_MinQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 2-0
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

### BR's for GRPC metasim (ensuring 2 SoC setup is correct)

xilinx_u250_grpc:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimGRPCMinimalConfig
  PLATFORM_CONFIG: BaseXilinxAlveoU250Config
  TARGET_SPLIT_CONFIG: 2-1
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

### BR's for GRPC metasim but split (ensuring 2 SoC setup is correct)

xilinx_u250_grpc_2fpga_base_minimal:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimGRPCMinimalConfig
  PLATFORM_CONFIG: Preserve_Remove_MinQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 2-1
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_grpc_2fpga_p1_minimal:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimGRPCMinimalConfig
  PLATFORM_CONFIG: Preserve_Extract_MinQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 2-0
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

### BR's for GRPC (full 2 SoC setup)

xilinx_u250_grpc_2fpga_base:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimGRPCConfig
  PLATFORM_CONFIG: Preserve_Remove_GRPC2FPGAQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 2-1
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml

xilinx_u250_grpc_2fpga_p1:
  PLATFORM: xilinx_alveo_u250
  TARGET_PROJECT: firesim
  DESIGN: FireSim
  TARGET_CONFIG: FireSimGRPCConfig
  PLATFORM_CONFIG: Preserve_Extract_GRPC2FPGAQSFPXilinxAlveoConfig
  TARGET_SPLIT_CONFIG: 2-0
  deploy_quintuplet: null
  platform_config_args:
    fpga_frequency: 10
    build_strategy: GRPC
  post_build_hook: null
  metasim_customruntimeconfig: null
  bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u250.yaml
